mirek/mirek/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('supervision/', include('supervision.urls', namespace='supervision')),
    path('accounts/', include('django.contrib.auth.urls')),
]

mirek/supervision/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'supervision'

urlpatterns = [
    path('all_controls/', All_controls.as_view(), name='allcontrols'),
    path('controls/<option>/', Filter_controls.as_view(), name='filtercontrols'),
    path('new_control', NewControl.as_view(), name='newcontrol'),
    path('update_control/<int:pk>', UpdateControlView.as_view(), name='updatecontrol'),
    path('delete_control/<int:pk>', DeleteControlView.as_view(), name='deletecontrol'),
    path('make_control/<int:control_id>', make_control_view, name='makecontrol'),
]

mirek/supervision/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date, timedelta
# Create your models here.




class Control(models.Model):
	SHAFTS = {
		('leon4', 'Leon IV'),
		('leon2', 'Leon II')
	}

	AREAS = {
		('nadszybie', 'nadszybie'),
		('zrab', 'zrąb'),
		('600', '600'),
		('800', '800'),
		('1000', '1000'),
		('1067', '1067'),
		('1150', '1150'),
		('1200', '1200'),
	}

	CYCLE = {
		('7', 'tygodniówka'),
		('30', 'miesiączka'),
		('42', 'sześcio-tygodniowa'),
		('90', 'kwartalna'),
		('180', 'pół-roczna'),
		('365', 'roczna'),
		('730', 'co dwa lata'),
		('1825', 'co pięć lat'),

	}

	mineshaft = models.CharField(max_length=12, choices=SHAFTS, default='leon2')
	area = models.CharField(max_length=12, choices=AREAS, default='800')
	installation = models.CharField(max_length=200)
	comments = models.CharField(max_length=255, blank=True)
	cycle = models.CharField(max_length=30, choices=CYCLE, default='7')

	performing = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	next_control_date = models.DateField(default=timezone.now)

	@property
	def last_control_date(self):
		"""date of last control"""
		td = timedelta(days=int(self.cycle))
		return self.next_control_date - td

	@property
	def late_control(self):
		td = self.next_control_date - date.today()
		# print(td.days)
		if td.days <= 0:
			return False
		else:
			return True


	def __str__(self):
		return f'{self.mineshaft},{self.area},{self.installation} ({self.cycle})'

mirek/supervision/forms.py
from django.forms import *
from .models import Control

class ControlForm(ModelForm):
    class Meta:
        model = Control
        fields = '__all__'
        #exclude = ['performing']
        # widgets = {
        #     'next_control_date': SelectDateWidget(),
        #     'performing': TextInput(attrs={'disabled': True}),
        # }
class MakeControlForm(Form):
    date = DateField()
    

mirek/supervision/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, TemplateView, CreateView, DetailView,\
    UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

from .models import Control
from .forms import *
from datetime import date, timedelta
# Create your views here.

# def all_controls(request):
#     all_controls = Control.objects.all()
#     context = {'controls': all_controls}
#     return render(request, 'controls.html', context)

class All_controls(LoginRequiredMixin, ListView):
    template_name = 'controls.html'
    model = Control
    context_object_name = 'controls'
    #queryset = Control.objects.all()
    #paginate_by = 10
    ordering = ['next_control_date']

class Filter_controls(LoginRequiredMixin, ListView):
    template_name = 'controls.html'
    context_object_name = 'controls'
    ordering = ['next_control_date']
    #paginate_by = 10

    def get_queryset(self):
        option = self.kwargs['option']
        if option == 'late':
            return Control.objects.filter(next_control_date__lte=date.today())
        elif option == 'incoming':
            td = timedelta(days=15) + date.today()
            return Control.objects.filter(next_control_date__gt=date.today()).\
            filter(next_control_date__lte=td)
        else:
            return Control.objects.filter(mineshaft=option)


class NewControl(LoginRequiredMixin, CreateView):
    model = Control
    #form_class = ControlForm
    #fields = ['mineshaft', 'area', 'installation', 'comments', 'cycle', 'next_control_date']
    fields = '__all__'
    template_name = 'control_form.html'
    success_url = reverse_lazy('supervision:allcontrols')

    def get_initial(self):
        performing = self.request.user
        return {'performing': performing}

class UpdateControlView(LoginRequiredMixin, UpdateView):
    model = Control
    fields = '__all__'
    template_name = 'control_form.html'
    success_url = reverse_lazy('supervision:allcontrols')
    context_object_name = 'control'

def make_control_view(request, control_id):
    form = MakeControlForm(initial={'date':date.today()})
    if request.method == 'POST':
        form = MakeControlForm(request.POST)
        if form.is_valid():
            next_date = form.cleaned_data['date']
            control = get_object_or_404(Control, pk=control_id)
            control.next_control_date = next_date
            control.save()
        return redirect('supervision:allcontrols')
    return render(request, 'control_make.html', {'form': form})


class DeleteControlView(LoginRequiredMixin, DeleteView):
    model = Control
    template_name = 'control_delete.html'
    success_url = reverse_lazy('supervision:allcontrols')

mirek/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/120047614f.js" crossorigin="anonymous"></script>
    <title>MIREK_Project!</title>
    <style>
      body {background-color: snow;}
    </style>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{%url 'supervision:allcontrols'%}"><i class="fas fa-clipboard-check"></i>_MIREK_Project
          {% if user.is_authenticated %}
          <p></p>
              <h6>zalogowano: {{ user.get_username }}</h6>
          {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>

            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{%url 'logout'%}">logout</a>
              <a class="nav-item nav-link" href="{%url 'password_change'%}">zmień hasło</a>
            {% else %}
              <a class="nav-item nav-link" href="{%url 'login'%}">login</a>
            {% endif %}

            <a class="nav-item nav-link" href="{%url 'supervision:allcontrols'%}">Wszystkie kontrole</a>
            <a class="nav-item nav-link" href="{%url 'supervision:newcontrol'%}">Nowa kontrola</a>
            <a class="nav-item nav-link" href="{%url 'admin:index' %}">admin</a>
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
          </div>
        </div>
          <!-- Navbar content -->
      </nav>

        {% block content %} {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

mirek/templates/control_delete.html
{% extends 'base.html' %}
<!-- {% load bootstrap4 %} -->

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Napewno usunąć pozycję ?</p>
        <i class="fas fa-check-circle"></i>
        <input class="btn btn-success" type="submit" value="Usuń">
    </form>
    <p></p>
    <i class="fas fa-minus-circle"></i>
<a href="{% url 'supervision:allcontrols'%}"><button type="button" class="btn btn-success">NIE</button></a>

{% endblock %}

mirek/templates/control_form.html
{% extends 'base.html' %}
<!-- {% load bootstrap4 %}
{% load crispy_forms_tags %} -->

{% block content %}
    <form method="post">
        {% csrf_token %}
        <!-- {% crispy form %} -->
        {{ form.as_p }}
        <p></p>
        <i class="far fa-save"></i>
        <input class="btn btn-success" type="submit" value="Zapisz">
    </form>
    <p></p>
    <i class="fas fa-minus-circle"></i>
<a href="{% url 'supervision:allcontrols'%}"><button type="button" class="btn btn-success">NIE</button></a>
  <p></p>
  {% if control %}
  <i class="fas fa-trash-alt"></i>
<a href="{% url 'supervision:deletecontrol' control.id %}"><button type="button" class="btn btn-danger">USUŃ</button></a>
  {% endif %}
{% endblock %}

mirek/templates/control_make.html
{% extends 'base.html' %}
<!-- {% load bootstrap4 %}
{% load crispy_forms_tags %} -->

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Wykonałeś kontrolę?</p>
        {{ form.as_p }}
        <p></p>
        <i class="fas fa-check-circle"></i>
        <input class="btn btn-success" type="submit" value="Potwierdź">
    </form>
    <p></p>
    <i class="fas fa-minus-circle"></i>
<a href="{% url 'supervision:allcontrols'%}"><button type="button" class="btn btn-success">NIE</button></a>

{% endblock %}

mirek/templates/controls.html
{% extends 'base.html' %}

{% block content %}
<div class="">
  <br>
</div>
<a href="{% url 'supervision:filtercontrols' 'leon2'%}"><button type="button" class="btn btn-success">Leon II</button></a>
<a href="{% url 'supervision:filtercontrols' 'leon4'%}"><button type="button" class="btn btn-success">Leon IV</button></a>
<a href="{% url 'supervision:allcontrols'%}"><button type="button" class="btn btn-success">wszystkie</button></a>

<a href="{% url 'supervision:filtercontrols' 'late'%}"><button type="button" class="btn btn-danger">przepadnięte</button></a>
<a href="{% url 'supervision:filtercontrols' 'incoming'%}"><button type="button" class="btn btn-warning">nadchodzące</button></a>


      <h1>Kontrole:</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Szyb</th>
            <th scope="col">Poziom</th>
            <th scope="col">Urządzenie</th>
            <th scope="col">Ostatnia kontrola</th>
            <th scope="col">Cykl</th>
            <th scope="col">Następna kontrola</th>
            <th scope="col">Wykon</th>
          </tr>
        </thead>
        <tbody>
          {% for control in controls %}
            <tr>

              <td>{{ forloop.counter }} <a href="{% url 'supervision:updatecontrol' control.pk %}"><i class="fas fa-binoculars"></i></a></td>
              <td>{{ control.get_mineshaft_display }}</td>
              <td>{{ control.get_area_display }}</td>
              <td>{{ control.installation }}</td>
              <td>{{ control.last_control_date }}</td>
              <td>{{ control.get_cycle_display }}</td>
              <td>{{ control.next_control_date }}</td>
              <td>{% if control.late_control %}
                    <i class="far fa-thumbs-up"></i>
                  {% else %}
                    <i style="color:red;" class="fas fa-skull-crossbones"></i>
                  {% endif %}
                  <a href="{% url 'supervision:makecontrol' control.pk %}"><i class="fas fa-briefcase"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

{% endblock %}